# Generated by Django 3.2.11 on 2023-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_company_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
