# Generated by Django 3.2.11 on 2023-03-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230313_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytoken',
            options={'ordering': ('-created_time',)},
        ),
    ]
