# Generated by Django 3.2.11 on 2023-03-15 05:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230314_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=users.models.generate_id, editable=False, max_length=7, primary_key=True, serialize=False),
        ),
    ]
