# Generated by Django 3.2.11 on 2023-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.AddField(
            model_name='company',
            name='user_agent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
