# Generated by Django 3.2.11 on 2023-03-22 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230321_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 22, 3, 26, 27, 280340, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='companytoken',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 22, 3, 26, 27, 280340, tzinfo=utc), null=True),
        ),
    ]
