# Generated by Django 3.2.11 on 2023-03-22 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230321_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='companytoken',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
