# Generated by Django 3.2.11 on 2023-03-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230322_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcodes',
            name='time',
        ),
        migrations.AddField(
            model_name='emailcodes',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
