# Generated by Django 3.2.11 on 2023-03-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230322_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcodes',
            name='email_code',
            field=models.IntegerField(default=874906, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
