# Generated by Django 3.2.11 on 2023-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20230322_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcodes',
            name='expired',
        ),
        migrations.AlterField(
            model_name='emailcodes',
            name='email_code',
            field=models.IntegerField(default=194830, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
