# Generated by Django 3.2.11 on 2023-03-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20230322_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcodes',
            name='email_code',
            field=models.IntegerField(default=367296, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
