# Generated by Django 3.2.11 on 2023-04-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_emailcodes_email_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytoken',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
    ]
